version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql-5.7
    restart: always
    environment:
      MYSQL_DATABASE: "ecom"
      MYSQL_USER: "sample"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mysql-db:/va/lib/mysql

volumes:
  mysql-db:
